name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --configuration release
      - name: Get tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Archive
        run: | 
          mv "`swift build --show-bin-path --configuration release`/ACKLocalization" .
          zip -r "acklocalization-${{ steps.get_version.outputs.VERSION }}.zip" LICENSE ACKLocalization
      - uses: xresloader/upload-to-github-release@v1.6.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: acklocalization-${{ steps.get_version.outputs.VERSION }}.zip
          tags: true
          draft: false
      - name: Install gems
        run: bundle install