name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - name: Build
        run: swift build --static-swift-stdlib --configuration release
      - name: Get tag name
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Archive
        run: | 
          mv "`swift build --show-bin-path --configuration release`/ACKLocalization" .
          zip -r "acklocalization-${{ steps.get_version.outputs.VERSION }}.zip" LICENSE ACKLocalization
      - uses: xresloader/upload-to-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: acklocalization-${{ steps.get_version.outputs.VERSION }}.zip
          tags: true
          draft: false
      - name: Install gems
        run: bundle install
      - name: Push podspec
        run: bundle exec pod trunk push --skip-import-validation --skip-tests --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
